(function () {
  const LANG_KEY = "lang";
  const DICT = {
    hu: {
      header_sub: "Hangszer, hang, inspiráció",
      menu_btn: "Menü",
      back: "Vissza",
      back_home: "Vissza a főoldalra",
      name_label: "Név",
      name_placeholder: "Teljes név",
      email_placeholder: "email@pelda.hu",
      address_label: "Cím",
      address_placeholder: "Utca, házszám",
      city_label: "Város",
      city_placeholder: "Budapest",
      postal_label: "Irányítószám",
      postal_placeholder: "1234",
      cart_title: "Kosár",
      cart_product: "Termék",
      cart_price: "Ár",
      cart_qty: "Mennyiség",
      cart_sub: "Részösszeg",
      cart_total: "Összesen",
      cart_clear: "Kosár ürítése",
      cart_confirm_title: "Kosár ürítése",
      cart_confirm_desc: "Biztos törlöd a kosár tartalmát?",
      cart_deleted: "Kosár törölve.",
      order_btn: "Fizetés",
      billing_title: "Számlázás",
      shipping_options: "Szállítási mód",
      ship_gls: "GLS futár",
      ship_mpl: "MPL futár",
      ship_foxpost: "Foxpost automata",
      ship_pickup: "Személyes átvétel",
      shipping_free_over_300k: "300 000 Ft felett a szállítás ingyenes.",
      shipping_free_applied: "Aktív kedvezmény.",
      summary_title: "Összegzés",
      summary_price_label: "Termékek",
      summary_fee_label: "Szállítás",
      summary_tax_label: "ÁFA",
      summary_method_label: "Fizetési mód",
      summary_total_label: "Végösszeg",
      pay_title: "Fizetés",
      pay_sub: "Válassz fizetési módot",
      pay_button: "Fizetek",
      pay: "Fizetés",
      card_title: "Kártyás fizetés",
      card_number_label: "Kártyaszám",
      card_number_placeholder: "1234 5678 9012 3456",
      expiry_label: "Lejárat",
      expiry_placeholder: "HH/ÉÉ",
      cvv_label: "CVV",
      cvv_placeholder: "123",
      purchased_title: "Megvásárolt termékek",
      currency_title: "Pénzváltás",
      currency_heading: "Valuta váltó",
      currency_amount_placeholder: "Összeg",
      currency_convert: "Átváltás",
      admin_title: "Admin felület",
      admin_loading: "Betöltés...",
      admin_th_id: "ID",
      admin_th_username: "Felhasználónév",
      admin_th_email: "Email",
      admin_th_role: "Szerep",
      admin_th_pic: "Kép",
      admin_th_action: "Művelet",
      admin_confirm_title_default: "Megerősítés",
      admin_confirm_text_default: "Biztos vagy benne?",
      admin_confirm_yes: "Igen",
      admin_confirm_no: "Nem",
      cancel: "Mégse",
      foxpost_title: "Foxpost átvétel",
      foxpost_sub: "Válassz Foxpost automatát",
      foxpost_search_placeholder: "Keress automata...",
      foxpost_selected_prefix: "Kiválasztva:",
      foxpost_yes: "Igen",
      foxpost_no: "Nem",
      foxpost_close: "Bezárás",
      privacy_page: "Adatvédelem",
      terms_page: "ÁSZF",
      warranty_page: "Garancia",
      shipping_page: "Szállítás",
      contacts_page: "Elérhetőségek",
      info_terms_h1: "Általános Szerződési Feltételek",
      info_privacy_h1: "Adatvédelmi Tájékoztató",
      info_shipping_h1: "Szállítás és Fizetés",
      info_warranty_h1: "Garancia",
      info_contacts_h1: "Elérhetőségeink",
      info_terms_title: "ÁSZF - KEB Hangszerbolt",
      info_shipping_title: "Szállítás és Fizetés - KEB Hangszerbolt",
      info_warranty_title: "Garancia - KEB Hangszerbolt",
      info_privacy_title: "Adatvédelmi Tájékoztató - KEB Hangszerbolt",
      info_contacts_title: "Elérhetőségek - KEB Hangszerbolt",
      info_terms_intro: "Tájékoztató jellegű, demo tartalom - nem valódi szolgáltatás.",
      info_terms_s1_h: "1. Általános tudnivalók",
      info_terms_s1_p: "A KEB Hangszerbolt gyakorló projekt. A termékek, árak, leírások és szolgáltatások fiktívek.",
      info_terms_s2_h: "2. Vásárlás és rendelés",
      info_terms_s2_l1: "A rendelés nem jön létre, mivel az oldal demó célú.",
      info_terms_s2_l2: "A kosár funkció kizárólag vizuális, oktatási célt szolgál.",
      info_terms_s2_l3: "Szállítás és futárszolgálat valós formában nincs.",
      info_terms_s3_h: "3. Adatkezelés",
      info_terms_s3_p: "A rendszer nem gyűjt valós személyes adatokat, a megadott információk demó jellegűek.",
      info_terms_s4_h: "4. Garancia és felelősség",
      info_terms_s4_p: "A projekt nem vállal felelősséget valós károkozásért, a tartalom oktatási célokra készült.",
      info_terms_s5_h: "5. Felhasználói jogok",
      info_terms_s5_l1: "Az oldalt szabadon böngészheted és tesztelheted.",
      info_terms_s5_l2: "A tartalom oktatási célra felhasználható.",
      info_terms_s5_l3: "Ez nem kereskedelmi oldal.",
      info_shipping_intro: "Áttekintés a szállítási módokról és fizetési lehetőségekről.",
      info_shipping_s1_h: "Szállítási módok",
      info_shipping_s1_l1: "Házhozszállítás futárral - 1-3 munkanap",
      info_shipping_s1_l2: "Foxpost automata - 2-4 munkanap",
      info_shipping_s1_l3: "Személyes átvétel - ingyenes",
      info_shipping_s2_h: "Hangszer-specifikus csomagolás",
      info_shipping_s2_l1: "Gitár - párnázott doboz",
      info_shipping_s2_l2: "Billentyű - vastag habszivacs",
      info_shipping_s2_l3: "Hangfal - raklapos csomag",
      info_shipping_s3_h: "Fizetési lehetőségek",
      info_shipping_s3_l1: "Bankkártya",
      info_shipping_s3_l2: "Utánvét",
      info_shipping_s3_l3: "Átutalás",
      info_shipping_s4_h: "Szállítási idő",
      info_shipping_s4_p1: "Raktáron lévő termék: 1-3 nap",
      info_shipping_s4_p2: "Rendelésre: 5-14 nap",
      info_warranty_intro: "Ez a felület demó célú, a garanciális információk nem valósak.",
      info_warranty_s1_h: "Garancia tájékoztató",
      info_warranty_s1_p: "A KEB Hangszerbolt jelen weboldala demonstrációs projekt, a tartalmak nem jelentenek valós garanciát.",
      info_warranty_s2_h: "Mit jelent ez?",
      info_warranty_s2_l1: "A termékek fiktívek, az árak és szolgáltatások is.",
      info_warranty_s2_l2: "Valós szerviz vagy garanciális ügyintézés nem történik.",
      info_warranty_s2_l3: "A felület kizárólag oktatási célokat szolgál.",
      info_warranty_s3_h: "Jó hír",
      info_warranty_s3_p: "A gyakorló projektnek köszönhetően bátran tesztelheted a funkciókat, következmény nélkül.",
      info_privacy_intro: "Demó projekt: a tartalom oktatási célú, nem valós adatkezelés.",
      info_privacy_s1_h: "1. Milyen adatokat kezelünk?",
      info_privacy_s1_p: "A megadott adatok nem kerülnek valós adatbázisba, csak demonstrációs célra szolgálnak.",
      info_privacy_s2_h: "2. Hol tárolódnak az adatok?",
      info_privacy_s2_p: "A tesztadatok helyileg a böngészőben tárolódhatnak (pl. localStorage).",
      info_privacy_s3_h: "3. Mire használjuk az adatokat?",
      info_privacy_s3_p: "Csak a felület működésének szimulálására, valós üzleti feldolgozás nincs.",
      info_privacy_s4_h: "4. Milyen jogaid vannak?",
      info_privacy_s4_p: "Bármikor törölheted vagy módosíthatod a böngészőben tárolt adatokat.",
      info_privacy_s5_h: "5. Kapcsolat",
      info_privacy_s5_p: "Kérdés esetén írj nyugodtan: kamu@kamuoldal.hu",
      info_contacts_intro: "Kapcsolati adatok - demó projekt, nem valós ügyfélszolgálat.",
      info_contacts_s1_h: "Ügyfélszolgálat",
      info_contacts_s1_p1: "Telefon: +36 30 000 0000",
      info_contacts_s1_p2: "Email: demo@keb-hangszerbolt.hu",
      info_contacts_s2_h: "Nyitvatartás",
      info_contacts_s2_l1: "Hétfő-Péntek: 9:00-18:00",
      info_contacts_s2_l2: "Szombat: 10:00-14:00",
      info_contacts_s2_l3: "Vasárnap: Zárva",
      info_contacts_s3_h: "Bemutatóterem",
      info_contacts_s3_p1: "Pécs, Fő utca 12.",
      info_contacts_s3_p2: "Parkolás ingyenes a bolt előtt.",
      search: "Keresés...",
      promo_title: "Akciók",
      promo_sub: "Heti leárazások",
      jump: "Ugrás",
      rec_title: "Ajánlott",
      rec_sub: "Népszerű hangszerek",
      promo_tag: "Vedd meg most!",
      view: "Megnézem",
      promo_title_long: "Akciók",
      promo_desc: "Friss leárazások a héten. Kattints és nézd meg a részleteket.",
      promo_cart: "Akciós kosár",
      rec_title_long: "Ajánlott hangszerek",
      rec_desc: "Válogatás a legnépszerűbb cuccokból.",
      view_all: "Teljes kínálat",
      why_desc: "Gyors rendelés, biztos csomagolás, zenészbarát támogatás.",
      feature_safe_title: "Biztonságos csomag",
      feature_safe_desc: "Dupla védelem, út közben is biztos.",
      feature_fast_title: "Gyors kiszállítás",
      feature_fast_desc: "Raktáron lévő termékek 24-48 óra.",
      feature_real_title: "Valódi zenészek",
      feature_real_desc: "Ajánlások gyakorló muzsikusoktól.",
      reviews_desc: "Pár mondat a zenészektől.",
      quote_1_text: "Nagyon barátságos oldal, gyorsan megtaláltam, amit kerestem.",
      quote_2_text: "Szuper hangszerek, korrekt árak. Ajánlom!",
      quote_3_text: "A rendelés gyors volt, a csomagolás profi.",
      quote_4_text: "Végre egy zenészbarát webshop.",
      quote_title: "Vélemény írása",
      name: "Név",
      tag_site: "Az oldal",
      tag_gitar: "Gitár",
      tag_bass: "Basszus gitár",
      tag_drum: "Dob",
      tag_keys: "Billentyű",
      tag_mic: "Mikrofon",
      tag_speakers: "Hangfal",
      tag_accessories: "Tartozék",
      tab_products: "Termékek",
      tab_about: "Rólunk",
      tab_other: "Egyéb",
      wishlist_page_title: "Kívánságlista",
      wishlist_page_desc: "Itt látod a szívecskével mentett termékeket.",
      wishlist_clear: "Lista ürítése",
      wishlist_empty: "Még nincs mentett termék.",
      wishlist_open: "Megnyitás",
      wishlist_remove: "Törlés",
      tab_services: "Szolgáltatások",
      wishlist_title: "Kívánságlista",
      chat_title: "Chat",
      chat_intro: "Itt tudsz írni más felhasználóknak hirdetésről vagy bármi másról.",
      chat_threads: "Beszélgetések",
      chat_empty: "Nincs még üzeneted.",
      chat_user: "Felhasználó",
      chat_write: "Írj üzenetet...",
      chat_badge_one: "1 üzenet",
      chat_badge_many: "Új üzenetek",
      wishlist_added: "Kívánságlistához téve!",
      wishlist_view: "Kívánságlista megtekintése",
      chat_item: "Hirdetés",
      chat_login_required: "Bejelentkezés szükséges a chathez.",
      video_caption: "Friss hangulatvideó a közösségről. Fent váltakozva gyors linket kapsz a használt piactér és a Bandakereső oldalra.",
      video_link_used: "Használt piactér",
      video_link_band: "Bandakereső oldal",
      video_muted: "Némítva",
      video_unmuted: "Hanggal",
      side_panel: "Menü",
      privacy: "Adatvédelem",
      shipping: "Szállítás",
      terms: "ÁSZF",
      warranty: "Garancia",
      contacts: "Elérhetőségeink",
      footer_pay_title: "Biztonságos vásárlás és fizetés",
      footer_pay_desc: "Fizessen biztonságosan titkosított kapcsolaton keresztül. (Teszt oldal, ez nem létezik)",
      footer_bank_transfer: "Banki átutalás",
      footer_benefits: "Előnyök",
      benefit_warranty: "3 év garancia",
      benefit_refund: "30 napos pénzvisszafizetés",
      benefit_service: "Szerviz és javítás",
      benefit_support: "Szakértői támogatás",
      benefit_test: "Tesz oldal",
      footer_services: "Szolgáltatások",
      shipping_pay: "Szállítás és fizetés",
      footer_copyright: "© 2025 KEB Hangszerbolt - Minden jog fenntartva. Vizsga oldal.",
      no_results: "Nincs találat.",
      cat_gitar: "Gitár",
      cat_bass: "Basszus gitár",
      cat_drum: "Dob",
      cat_keys: "Billentyű",
      cat_mic: "Mikrofon",
      cat_speakers: "Hangfal",
      cat_accessories: "Tartozékok",
      cat_accessories_desc: "Kiegészítők, kábelek, állványok és minden apróság egyben.",
      cat_bass_desc: "Mély tartomány, feszes groove, modern és vintage hangzások.",
      cat_drum_desc: "Akusztikus és elektromos dobok kezdőktől profikig.",
      cat_keys_desc: "Szintik, stage pianók és otthoni gyakorló hangszerek.",
      cat_mic_desc: "Színpadra, stúdióba és streameléshez válogatott modellek.",
      cat_speakers_desc: "Stúdiómonitorok, party hangfalak és hordozható kedvencek.",
      title_cat_gitar: "KEB Gitárok",
      title_cat_bass: "KEB Basszus gitárok",
      title_cat_drum: "KEB Dobszettek",
      title_cat_keys: "KEB Billentyűs hangszerek",
      title_cat_mic: "KEB Mikrofonok",
      title_cat_speakers: "KEB Hangfalak",
      title_cat_accessories: "KEB Tartozékok",
      min_label: "Min",
      max_label: "Max",
      huf_label: "Ft",
      why_title: "Miért ajánljuk?",
      shipping_title: "Szállítás",
      shipping_desc1: "Raktáron: 1–3 nap · Rendelésre: 5–14 nap",
      shipping_desc2: "Biztonságos csomagolás, zenészbarát ügyintézés.",
      reviews_title: "Vélemények",
      prev: "Előző",
      next: "Következő",
      details: "Részletek",
      add_to_cart: "Kosárba",
      added_to_cart_btn: "Kosárba téve!",
      sample: "Hangminta:",
      sample_title: "Hangminta",
      reviews: "Vélemények:",
      loading: "Betöltés...",
      product_desc: "{name} a(z) {category} kategóriából. Prémium minőség, megbízható hangzás.",
      spec_category: "Kategória",
      spec_shipping: "Szállítás: 24-48 óra raktáron",
      spec_warranty: "Garancia: 3 év",
      spec_setup: "Beállítás: az első hangolás ajándék",
      why_text: "Miért ezt a(z) {category} hangszert válaszd? Stabil, szép hang és strapabíró kivitel.",
      write_review: "Írj véleményt...",
      send: "Küldés",
      added_to_cart: "Kosárba helyezve!",
      must_login_review: "Be kell jelentkezned a vélemény írásához!",
      delete: "Törlés",
      review_already: "Már írtál véleményt.",
      review_need_text: "Írj valamit és válassz csillagot!",
      review_exists_alert: "Már írtál véleményt!",
      confirm_delete: "Biztos törlöd?",
      no_reviews: "Nincs még vélemény.",
      network_error: "Hálózati hiba",
      bad_json: "Nem JSON válasz",

      email_label: "Email",
      register_title: "Regisztráció",
      register_success: "Sikeres regisztráció!",
      register_error: "Hiba:",

      account_title: "Fiókom",
      account_back: "← Vissza a főoldalra",
      account_login_tab: "Bejelentkezés",
      account_register_tab: "Regisztráció",
      account_admin_tab: "Admin",
      account_login_title: "Bejelentkezés",
      account_register_title: "Regisztráció",
      account_admin_title: "Admin bejelentkezés",
      account_username_or_email: "Felhasználónév vagy Email",
      account_password: "Jelszó",
      account_username: "Felhasználónév",
      account_admin_name: "Admin név",
      account_username_hint: "3-32 karakter, betűvel kezdődjön, csak betű/szám/._-",
      account_login_btn: "Bejelentkezés",
      account_register_btn: "Regisztráció",
      account_admin_btn: "Belépés",
      account_welcome: "Üdv {name}!",
      account_profile_upload: "Profilkép feltöltése",
      account_delete: "Fiók törlése",
      account_logout: "Kijelentkezés",
      account_required_fields: "✖ Minden mező kötelező!",
      account_fix_fields: "✖ Javítsd a hibás mezőket!",
      account_username_len: "✖ A felhasználónév 3-32 karakter legyen.",
      account_username_format: "✖ A név betűvel kezdődjön, csak betű/szám/._- lehet benne.",
      account_username_separators: "✖ Nem lehet két speciális jel egymás mellett.",
      account_username_letters: "✖ Legalább 3 betű legyen a felhasználónévben.",
      account_username_repeat: "✖ Túl sok ismétlődő karakter.",
      account_invalid_email: "✖ Érvénytelen email formátum.",
      account_password_min: "✖ A jelszó legalább 6 karakter legyen.",
      account_login_success: "✔ Sikeres bejelentkezés!",
      account_register_success: "✔ Sikeres regisztráció! Jelentkezz be.",
      account_invalid_login: "✖ Hibás adatok!",
      account_not_admin: "✖ Ez NEM admin fiók!",
      account_token_expired: "✖ Lejárt token. Jelentkezz be újra.",
      account_no_file: "Nincs fájl kiválasztva!",

      profile_title: "Profil",
      profile_email_label: "Email:",
      profile_back: "⬅ Vissza",
      profile_logout_btn: "Kijelentkezés",
      profile_upload_btn: "Profilkép feltöltése",
      profile_file_missing: "Nincs fájl kiválasztva!",
      profile_updated: "Profil frissítve!",
      profile_loading: "Betöltés...",
      theme_toggle: "Téma váltás",

      used_title: "Használt eladó cuccok",
      used_short_desc: "Használt cuccok.",
      used_subtitle: "Adj fel használt cuccot vagy alkudj korrekt ajánlatot.",
      used_desc: "A piactérben a felhasználók ajánlatot tehetnek, az eladó pedig elfogadhatja vagy elutasíthatja.",
      used_add_title: "Termék feltöltése",
      used_login_hint: "Jelentkezz be a termék feltöltéséhez.",
      used_title_label: "Termék neve",
      used_price_label: "Ár (Ft)",
      used_category_label: "Kategória",
      used_condition_label: "Állapot",
      used_desc_label: "Leírás",
      used_image_label: "Kép",
      used_submit: "Feltöltés",
      used_search: "Keresés...",
      used_all: "Összes",
      used_mode_all: "Minden ajánlat",
      used_mode_mine: "Saját termékeim",
      used_filter_btn: "Szűrés",
      used_empty: "Nincs még eladó termék.",
      used_active: "Eladó",
      used_sold: "Eladva",
      used_sold_hint: "Ez a termék már elkelt.",
      used_login_offer: "Jelentkezz be, hogy ajánlatot tehess.",
      contact_user_btn: "Lépj kapcsolatba",
      offer_list_title: "Ajánlatok",
      offer_price_placeholder: "Ajánlat (Ft)",
      offer_send: "Ajánlat küldése",
      messages_btn: "Üzenetek",
      offer_none: "Még nincs ajánlat.",
      offer_pending: "Függőben",
      offer_accepted: "Elfogadva",
      offer_rejected: "Elutasítva",
      offer_accept: "Elfogad",
      offer_reject: "Elutasít",
      used_condition_new: "Újszerű",
      used_condition_good: "Jó",
      used_condition_used: "Használt",
      used_condition_fix: "Felújítandó",
      filter: "Szűrő",
      manufacturer: "Gyártó",
      price_category: "Árkategória",
      order_state: "Rendelkezésre állás",
      instant_shipping: "Azonnali szállításból",
      rating: "Értékelés",
      vibe_guitar_offers: "Gitár ajánlatok",
      vibe_bass_news: "Basszus újdonságok",
      vibe_used_market: "Használt piactér",
      vibe_band_search: "Zenekar kereső",
      cat_gitar_desc: "Elektromos, akusztikus és klasszikus modellek egy helyen.",
      page_label: "Oldal",

      band_title: "Bandakereső",
      band_short_desc: "Keress bandát.",
      band_subtitle: "Keress zenészeket és bandákat stílus, város és hangszer szerint.",
      band_desc: "Hozz létre bandaprofilodat, jelezd, milyen hangszert keresel, és vedd fel a kapcsolatot.",
      band_add_title: "Új banda felvétele",
      band_login_hint: "Jelentkezz be a banda létrehozásához.",
      band_name_label: "Banda neve",
      band_genre_label: "Stílus",
      band_city_label: "Város",
      band_looking_label: "Kit kerestek?",
      band_desc_label: "Leírás",
      band_contact_label: "Kapcsolat",
      band_contact_placeholder: "email / insta",
      band_image_label: "Bandakép",
      band_submit: "Banda mentése",
      band_update: "Banda frissítése",
      band_edit_mode: "Szerkesztés mód aktív.",
      band_edit_cancel: "Szerkesztés megszakítása",
      band_search: "Keresés...",
      band_genre_filter: "Stílus",
      band_city_filter: "Város",
      band_looking_filter: "Hangszer",
      band_filter_btn: "Szűrés",
      band_empty: "Nincs még banda a listában.",
      band_searching_for: "Keresett hangszer",
      band_chat_prefill: "Szia! Érdekel a bandád",
      posted_by: "Kirakta",
      edit: "Szerkesztés",

      profile_used_title: "Eladó termékeim",
      profile_used_empty: "Nincs feltöltött termék.",
      profile_bands_title: "Bandáim",
      profile_bands_empty: "Nincs még bandaprofil.",
      profile_rating_title: "Profil értékelés",
      profile_rating_empty: "Még nincs értékelés.",
      profile_rating_placeholder: "Írj pár sort...",
      profile_rating_send: "Értékelés küldése",
      profile_rating_login: "Jelentkezz be az értékeléshez.",

      verify_email_sent: "Hitelesítő email elküldve. Ellenőrizd a postaládádat.",
      verify_pending: "Ellenőrzés folyamatban...",
      verify_success: "Sikeres hitelesítés",
      verify_resend_sent: "Hitelesítő email újraküldve.",
      verify_resend_error: "Hiba: ",
      verify_resend_btn: "Hitelesítő email újraküldése"
    },
    en: {
      header_sub: "Instrument, sound, inspiration",
      menu_btn: "Menu",
      back: "Back",
      back_home: "Back to home",
      name_label: "Name",
      name_placeholder: "Full name",
      email_placeholder: "email@example.com",
      address_label: "Address",
      address_placeholder: "Street, house number",
      city_label: "City",
      city_placeholder: "Budapest",
      postal_label: "Postal code",
      postal_placeholder: "1234",
      cart_title: "Cart",
      cart_product: "Product",
      cart_price: "Price",
      cart_qty: "Quantity",
      cart_sub: "Subtotal",
      cart_total: "Total",
      cart_clear: "Clear cart",
      cart_confirm_title: "Clear cart",
      cart_confirm_desc: "Are you sure you want to clear the cart?",
      cart_deleted: "Cart cleared.",
      order_btn: "Checkout",
      billing_title: "Billing",
      shipping_options: "Shipping method",
      ship_gls: "GLS courier",
      ship_mpl: "MPL courier",
      ship_foxpost: "Foxpost locker",
      ship_pickup: "Store pickup",
      shipping_free_over_300k: "Shipping is free above 300,000 HUF.",
      shipping_free_applied: "Discount applied.",
      summary_title: "Summary",
      summary_price_label: "Products",
      summary_fee_label: "Shipping",
      summary_tax_label: "VAT",
      summary_method_label: "Payment method",
      summary_total_label: "Total",
      pay_title: "Payment",
      pay_sub: "Choose a payment method",
      pay_button: "Pay",
      pay: "Payment",
      card_title: "Card payment",
      card_number_label: "Card number",
      card_number_placeholder: "1234 5678 9012 3456",
      expiry_label: "Expiry",
      expiry_placeholder: "MM/YY",
      cvv_label: "CVV",
      cvv_placeholder: "123",
      purchased_title: "Purchased items",
      currency_title: "Currency exchange",
      currency_heading: "Currency converter",
      currency_amount_placeholder: "Amount",
      currency_convert: "Convert",
      admin_title: "Admin panel",
      admin_loading: "Loading...",
      admin_th_id: "ID",
      admin_th_username: "Username",
      admin_th_email: "Email",
      admin_th_role: "Role",
      admin_th_pic: "Image",
      admin_th_action: "Action",
      admin_confirm_title_default: "Confirm",
      admin_confirm_text_default: "Are you sure?",
      admin_confirm_yes: "Yes",
      admin_confirm_no: "No",
      cancel: "Cancel",
      foxpost_title: "Foxpost pickup",
      foxpost_sub: "Choose a Foxpost locker",
      foxpost_search_placeholder: "Search locker...",
      foxpost_selected_prefix: "Selected:",
      foxpost_yes: "Yes",
      foxpost_no: "No",
      foxpost_close: "Close",
      privacy_page: "Privacy",
      terms_page: "Terms",
      warranty_page: "Warranty",
      shipping_page: "Shipping",
      contacts_page: "Contact",
      info_terms_h1: "Terms and Conditions",
      info_privacy_h1: "Privacy Notice",
      info_shipping_h1: "Shipping and Payment",
      info_warranty_h1: "Warranty",
      info_contacts_h1: "Contact",
      info_terms_title: "Terms - KEB Instrument Shop",
      info_shipping_title: "Shipping and Payment - KEB Instrument Shop",
      info_warranty_title: "Warranty - KEB Instrument Shop",
      info_privacy_title: "Privacy Notice - KEB Instrument Shop",
      info_contacts_title: "Contact - KEB Instrument Shop",
      info_terms_intro: "Informational demo content - not a real service.",
      info_terms_s1_h: "1. General information",
      info_terms_s1_p: "KEB Instrument Shop is a practice project. Products, prices, descriptions and services are fictional.",
      info_terms_s2_h: "2. Purchase and order",
      info_terms_s2_l1: "Orders are not finalized because this site is for demo purposes.",
      info_terms_s2_l2: "The cart function is visual only and used for learning.",
      info_terms_s2_l3: "There is no real shipping or courier service.",
      info_terms_s3_h: "3. Data handling",
      info_terms_s3_p: "The system does not collect real personal data, provided information is demo data.",
      info_terms_s4_h: "4. Warranty and liability",
      info_terms_s4_p: "The project does not accept liability for real damages; content is educational.",
      info_terms_s5_h: "5. User rights",
      info_terms_s5_l1: "You may freely browse and test the site.",
      info_terms_s5_l2: "Content may be used for educational purposes.",
      info_terms_s5_l3: "This is not a commercial website.",
      info_shipping_intro: "Overview of shipping methods and payment options.",
      info_shipping_s1_h: "Shipping methods",
      info_shipping_s1_l1: "Home delivery by courier - 1-3 business days",
      info_shipping_s1_l2: "Foxpost locker - 2-4 business days",
      info_shipping_s1_l3: "Personal pickup - free",
      info_shipping_s2_h: "Instrument-specific packaging",
      info_shipping_s2_l1: "Guitar - padded box",
      info_shipping_s2_l2: "Keyboard - thick foam protection",
      info_shipping_s2_l3: "Speaker - palletized package",
      info_shipping_s3_h: "Payment options",
      info_shipping_s3_l1: "Bank card",
      info_shipping_s3_l2: "Cash on delivery",
      info_shipping_s3_l3: "Bank transfer",
      info_shipping_s4_h: "Delivery time",
      info_shipping_s4_p1: "In-stock item: 1-3 days",
      info_shipping_s4_p2: "Made-to-order: 5-14 days",
      info_warranty_intro: "This page is for demo purposes; warranty information is not real.",
      info_warranty_s1_h: "Warranty information",
      info_warranty_s1_p: "The current KEB Instrument Shop website is a demonstration project; content does not represent real warranty.",
      info_warranty_s2_h: "What does this mean?",
      info_warranty_s2_l1: "Products are fictional, including prices and services.",
      info_warranty_s2_l2: "No real service center or warranty process is provided.",
      info_warranty_s2_l3: "The interface is for educational use only.",
      info_warranty_s3_h: "Good news",
      info_warranty_s3_p: "Because this is a practice project, you can test features freely without consequences.",
      info_privacy_intro: "Demo project: content is educational, not real data processing.",
      info_privacy_s1_h: "1. What data do we process?",
      info_privacy_s1_p: "Entered data is not stored in a real database; it is only for demonstration.",
      info_privacy_s2_h: "2. Where is data stored?",
      info_privacy_s2_p: "Test data may be stored locally in the browser (e.g., localStorage).",
      info_privacy_s3_h: "3. What do we use data for?",
      info_privacy_s3_p: "Only to simulate interface behavior; there is no real business processing.",
      info_privacy_s4_h: "4. What rights do you have?",
      info_privacy_s4_p: "You can delete or modify browser-stored data at any time.",
      info_privacy_s5_h: "5. Contact",
      info_privacy_s5_p: "For questions, write to: kamu@kamuoldal.hu",
      info_contacts_intro: "Contact details - demo project, not a real customer service.",
      info_contacts_s1_h: "Customer service",
      info_contacts_s1_p1: "Phone: +36 30 000 0000",
      info_contacts_s1_p2: "Email: demo@keb-hangszerbolt.hu",
      info_contacts_s2_h: "Opening hours",
      info_contacts_s2_l1: "Monday-Friday: 9:00-18:00",
      info_contacts_s2_l2: "Saturday: 10:00-14:00",
      info_contacts_s2_l3: "Sunday: Closed",
      info_contacts_s3_h: "Showroom",
      info_contacts_s3_p1: "Pecs, Fo utca 12.",
      info_contacts_s3_p2: "Free parking in front of the shop.",
      search: "Search...",
      promo_title: "Promotions",
      promo_sub: "Weekly discounts",
      jump: "Jump",
      rec_title: "Recommended",
      rec_sub: "Popular instruments",
      promo_tag: "Buy now!",
      view: "View",
      promo_title_long: "Promotions",
      promo_desc: "Fresh weekly discounts. Click and see the details.",
      promo_cart: "Promo cart",
      rec_title_long: "Recommended instruments",
      rec_desc: "A selection of the most popular gear.",
      view_all: "Full catalog",
      why_desc: "Fast ordering, safe packaging, musician-friendly support.",
      feature_safe_title: "Secure packaging",
      feature_safe_desc: "Double protection, safe on the road.",
      feature_fast_title: "Fast delivery",
      feature_fast_desc: "In-stock items in 24-48 hours.",
      feature_real_title: "Real musicians",
      feature_real_desc: "Recommendations from practicing musicians.",
      reviews_desc: "A few words from musicians.",
      quote_1_text: "Friendly site, I quickly found what I needed.",
      quote_2_text: "Great instruments, fair prices. Recommended!",
      quote_3_text: "Fast order and professional packaging.",
      quote_4_text: "Finally a musician-friendly shop.",
      quote_title: "Write a review",
      name: "Name",
      tag_site: "The site",
      tag_gitar: "Guitar",
      tag_bass: "Bass guitar",
      tag_drum: "Drums",
      tag_keys: "Keys",
      tag_mic: "Microphone",
      tag_speakers: "Speakers",
      tag_accessories: "Accessories",
      tab_products: "Products",
      tab_about: "About",
      tab_other: "Other",
      wishlist_page_title: "Wishlist",
      wishlist_page_desc: "Here you can see your heart-saved products.",
      wishlist_clear: "Clear list",
      wishlist_empty: "No saved products yet.",
      wishlist_open: "Open",
      wishlist_remove: "Delete",
      tab_services: "Services",
      wishlist_title: "Wishlist",
      chat_title: "Chat",
      chat_intro: "Message other users about listings or anything else here.",
      chat_threads: "Conversations",
      chat_empty: "You have no messages yet.",
      chat_user: "User",
      chat_write: "Write a message...",
      chat_badge_one: "1 message",
      chat_badge_many: "New messages",
      wishlist_added: "Added to wishlist!",
      wishlist_view: "View wishlist",
      chat_item: "Listing",
      chat_login_required: "Login is required to use chat.",
      video_caption: "Fresh community mood video. Above, quick links rotate between the used marketplace and Band Finder.",
      video_link_used: "Used marketplace",
      video_link_band: "Band finder page",
      video_muted: "Muted",
      video_unmuted: "With sound",
      side_panel: "Menu",
      privacy: "Privacy",
      shipping: "Shipping",
      terms: "Terms",
      warranty: "Warranty",
      contacts: "Contact",
      footer_pay_title: "Secure shopping and payment",
      footer_pay_desc: "Pay securely through an encrypted connection. (Test site, not real)",
      footer_bank_transfer: "Bank transfer",
      footer_benefits: "Benefits",
      benefit_warranty: "3-year warranty",
      benefit_refund: "30-day money back",
      benefit_service: "Service and repair",
      benefit_support: "Expert support",
      benefit_test: "Test site",
      footer_services: "Services",
      shipping_pay: "Shipping and payment",
      footer_copyright: "© 2025 KEB Instrument Shop - All rights reserved. Exam site.",
      no_results: "No results.",
      cat_gitar: "Guitar",
      cat_bass: "Bass guitar",
      cat_drum: "Drums",
      cat_keys: "Keys",
      cat_mic: "Microphone",
      cat_speakers: "Speakers",
      cat_accessories: "Accessories",
      cat_accessories_desc: "Accessories, cables, stands and all the small extras in one place.",
      cat_bass_desc: "Deep range, tight groove, modern and vintage tones.",
      cat_drum_desc: "Acoustic and electronic drums for beginners and pros.",
      cat_keys_desc: "Synths, stage pianos and home practice instruments.",
      cat_mic_desc: "Selected models for stage, studio and streaming.",
      cat_speakers_desc: "Studio monitors, party speakers and portable favorites.",
      title_cat_gitar: "KEB Guitars",
      title_cat_bass: "KEB Bass Guitars",
      title_cat_drum: "KEB Drum Kits",
      title_cat_keys: "KEB Keyboard Instruments",
      title_cat_mic: "KEB Microphones",
      title_cat_speakers: "KEB Speakers",
      title_cat_accessories: "KEB Accessories",
      min_label: "Min",
      max_label: "Max",
      huf_label: "HUF",
      why_title: "Why we recommend",
      shipping_title: "Shipping",
      shipping_desc1: "In stock: 1–3 days · Order: 5–14 days",
      shipping_desc2: "Safe packaging and musician-friendly support.",
      reviews_title: "Reviews",
      prev: "Previous",
      next: "Next",
      details: "Details",
      add_to_cart: "Add to cart",
      added_to_cart_btn: "Added!",
      sample: "Sample:",
      sample_title: "Sound sample",
      reviews: "Reviews:",
      loading: "Loading...",
      product_desc: "{name} from the {category} category. Premium quality, reliable sound.",
      spec_category: "Category",
      spec_shipping: "Shipping: 24-48h in stock",
      spec_warranty: "Warranty: 3 years",
      spec_setup: "Setup: first tuning included",
      why_text: "Why choose this {category} instrument? Stable tone and durable build.",
      write_review: "Write a review...",
      send: "Send",
      added_to_cart: "Added to cart!",
      must_login_review: "You must be logged in to write a review!",
      delete: "Delete",
      review_already: "You already wrote a review.",
      review_need_text: "Write something and pick a star!",
      review_exists_alert: "You already wrote a review!",
      confirm_delete: "Are you sure you want to delete?",
      no_reviews: "No reviews yet.",
      network_error: "Network error",
      bad_json: "Invalid JSON response",

      email_label: "Email",
      register_title: "Register",
      register_success: "Registration successful!",
      register_error: "Error:",

      account_title: "My account",
      account_back: "← Back to home",
      account_login_tab: "Login",
      account_register_tab: "Register",
      account_admin_tab: "Admin",
      account_login_title: "Login",
      account_register_title: "Register",
      account_admin_title: "Admin login",
      account_username_or_email: "Username or Email",
      account_password: "Password",
      account_username: "Username",
      account_admin_name: "Admin name",
      account_username_hint: "3-32 chars, start with a letter, only letters/numbers/._-",
      account_login_btn: "Login",
      account_register_btn: "Register",
      account_admin_btn: "Enter",
      account_welcome: "Welcome {name}!",
      account_profile_upload: "Upload profile picture",
      account_delete: "Delete account",
      account_logout: "Logout",
      account_required_fields: "✖ All fields are required!",
      account_fix_fields: "✖ Fix invalid fields before continuing.",
      account_username_len: "✖ Username must be 3-32 characters.",
      account_username_format: "✖ Username must start with a letter and only use letters, numbers, dot, underscore, dash.",
      account_username_separators: "✖ Two separator characters in a row are not allowed.",
      account_username_letters: "✖ Username must contain at least 3 letters.",
      account_username_repeat: "✖ Too many repeated characters.",
      account_invalid_email: "✖ Invalid email format.",
      account_password_min: "✖ Password must be at least 6 characters.",
      account_login_success: "✔ Login successful!",
      account_register_success: "✔ Registration successful! Please log in.",
      account_invalid_login: "✖ Invalid credentials!",
      account_not_admin: "✖ This is NOT an admin account!",
      account_token_expired: "✖ Token expired. Please log in again.",
      account_no_file: "No file selected!",

      profile_title: "Profile",
      profile_email_label: "Email:",
      profile_back: "⬅ Back",
      profile_logout_btn: "Logout",
      profile_upload_btn: "Upload profile picture",
      profile_file_missing: "No file selected!",
      profile_updated: "Profile updated!",
      profile_loading: "Loading...",
      theme_toggle: "Toggle theme",

      used_title: "Used marketplace",
      used_short_desc: "Used gear.",
      used_subtitle: "List your gear or negotiate fair offers.",
      used_desc: "Users can make offers and sellers can accept or reject them.",
      used_add_title: "Upload item",
      used_login_hint: "Log in to upload an item.",
      used_title_label: "Item title",
      used_price_label: "Price (HUF)",
      used_category_label: "Category",
      used_condition_label: "Condition",
      used_desc_label: "Description",
      used_image_label: "Image",
      used_submit: "Upload",
      used_search: "Search...",
      used_all: "All",
      used_mode_all: "All offers",
      used_mode_mine: "My items",
      used_filter_btn: "Filter",
      used_empty: "No items yet.",
      used_active: "Available",
      used_sold: "Sold",
      used_sold_hint: "This item has been sold.",
      used_login_offer: "Log in to make an offer.",
      contact_user_btn: "Contact seller",
      offer_list_title: "Offers",
      offer_price_placeholder: "Offer (HUF)",
      offer_send: "Send offer",
      messages_btn: "Messages",
      offer_none: "No offers yet.",
      offer_pending: "Pending",
      offer_accepted: "Accepted",
      offer_rejected: "Rejected",
      offer_accept: "Accept",
      offer_reject: "Reject",
      used_condition_new: "Like new",
      used_condition_good: "Good",
      used_condition_used: "Used",
      used_condition_fix: "Needs repair",
      filter: "Filter",
      manufacturer: "Brand",
      price_category: "Price range",
      order_state: "Availability",
      instant_shipping: "Instant shipping",
      rating: "Rating",
      vibe_guitar_offers: "Guitar offers",
      vibe_bass_news: "Bass news",
      vibe_used_market: "Used marketplace",
      vibe_band_search: "Band search",
      cat_gitar_desc: "Electric, acoustic and classical models in one place.",
      page_label: "Page",

      band_title: "Band finder",
      band_short_desc: "Find a band.",
      band_subtitle: "Find musicians and bands by style, city, and instrument.",
      band_desc: "Create a band profile, add what you are looking for, and connect.",
      band_add_title: "Add new band",
      band_login_hint: "Log in to create a band.",
      band_name_label: "Band name",
      band_genre_label: "Genre",
      band_city_label: "City",
      band_looking_label: "Looking for",
      band_desc_label: "Description",
      band_contact_label: "Contact",
      band_contact_placeholder: "email / insta",
      band_image_label: "Band image",
      band_submit: "Save band",
      band_update: "Update band",
      band_edit_mode: "Edit mode is active.",
      band_edit_cancel: "Cancel editing",
      band_search: "Search...",
      band_genre_filter: "Genre",
      band_city_filter: "City",
      band_looking_filter: "Instrument",
      band_filter_btn: "Filter",
      band_empty: "No bands yet.",
      band_searching_for: "Looking for",
      band_chat_prefill: "Hi! I'm interested in your band",
      posted_by: "Posted by",
      edit: "Edit",

      profile_used_title: "My items for sale",
      profile_used_empty: "No items uploaded.",
      profile_bands_title: "My bands",
      profile_bands_empty: "No band profile yet.",
      profile_rating_title: "Profile rating",
      profile_rating_empty: "No ratings yet.",
      profile_rating_placeholder: "Write a short review...",
      profile_rating_send: "Send rating",
      profile_rating_login: "Log in to rate.",

      verify_email_sent: "Verification email sent. Check your inbox.",
      verify_pending: "Verification in progress...",
      verify_success: "Verification successful",
      verify_resend_sent: "Verification email resent.",
      verify_resend_error: "Error: ",
      verify_resend_btn: "Resend verification email"
    },
    de: {
      header_sub: "Instrument, Klang, Inspiration",
      menu_btn: "Menü öffnen",
      back: "Zurück",
      back_home: "Zurück zur Startseite",
      name_label: "Name",
      name_placeholder: "Vollständiger Name",
      email_placeholder: "email@beispiel.de",
      address_label: "Adresse",
      address_placeholder: "Straße, Hausnummer",
      city_label: "Stadt",
      city_placeholder: "Budapest",
      postal_label: "Postleitzahl",
      postal_placeholder: "1234",
      cart_title: "Warenkorb",
      cart_product: "Produkt",
      cart_price: "Preis",
      cart_qty: "Menge",
      cart_sub: "Zwischensumme",
      cart_total: "Gesamt",
      cart_clear: "Warenkorb leeren",
      cart_confirm_title: "Warenkorb leeren",
      cart_confirm_desc: "Möchtest du den Warenkorb wirklich leeren?",
      cart_deleted: "Warenkorb geleert.",
      order_btn: "Zur Kasse",
      billing_title: "Rechnung",
      shipping_options: "Versandart",
      ship_gls: "GLS Kurier",
      ship_mpl: "MPL Kurier",
      ship_foxpost: "Foxpost Paketautomat",
      ship_pickup: "Abholung",
      shipping_free_over_300k: "Ab 300.000 HUF ist der Versand kostenlos.",
      shipping_free_applied: "Rabatt aktiv.",
      summary_title: "Zusammenfassung",
      summary_price_label: "Produkte",
      summary_fee_label: "Versand",
      summary_tax_label: "MwSt.",
      summary_method_label: "Zahlungsart",
      summary_total_label: "Gesamtsumme",
      pay_title: "Zahlung",
      pay_sub: "Wähle eine Zahlungsart",
      pay_button: "Bezahlen",
      pay: "Zahlung",
      card_title: "Kartenzahlung",
      card_number_label: "Kartennummer",
      card_number_placeholder: "1234 5678 9012 3456",
      expiry_label: "Ablauf",
      expiry_placeholder: "MM/JJ",
      cvv_label: "CVV",
      cvv_placeholder: "123",
      purchased_title: "Gekaufte Artikel",
      currency_title: "Währungswechsel",
      currency_heading: "Währungsrechner",
      currency_amount_placeholder: "Betrag",
      currency_convert: "Umrechnen",
      admin_title: "Admin-Bereich",
      admin_loading: "Lädt...",
      admin_th_id: "ID",
      admin_th_username: "Benutzername",
      admin_th_email: "E-Mail",
      admin_th_role: "Rolle",
      admin_th_pic: "Bild",
      admin_th_action: "Aktion",
      admin_confirm_title_default: "Bestätigung",
      admin_confirm_text_default: "Bist du sicher?",
      admin_confirm_yes: "Ja",
      admin_confirm_no: "Nein",
      cancel: "Abbrechen",
      foxpost_title: "Foxpost Abholung",
      foxpost_sub: "Wähle einen Foxpost-Automaten",
      foxpost_search_placeholder: "Automat suchen...",
      foxpost_selected_prefix: "Ausgewählt:",
      foxpost_yes: "Ja",
      foxpost_no: "Nein",
      foxpost_close: "Schließen",
      privacy_page: "Datenschutz",
      terms_page: "AGB",
      warranty_page: "Garantie",
      shipping_page: "Versand",
      contacts_page: "Kontakt",
      info_terms_h1: "Allgemeine Geschäftsbedingungen",
      info_privacy_h1: "Datenschutzhinweis",
      info_shipping_h1: "Versand und Zahlung",
      info_warranty_h1: "Garantie",
      info_contacts_h1: "Kontakt",
      info_terms_title: "AGB - KEB Instrumentenladen",
      info_shipping_title: "Versand und Zahlung - KEB Instrumentenladen",
      info_warranty_title: "Garantie - KEB Instrumentenladen",
      info_privacy_title: "Datenschutzhinweis - KEB Instrumentenladen",
      info_contacts_title: "Kontakt - KEB Instrumentenladen",
      info_terms_intro: "Hinweisinhalt im Demo-Format - kein echter Dienst.",
      info_terms_s1_h: "1. Allgemeine Hinweise",
      info_terms_s1_p: "Der KEB Instrumentenladen ist ein Übungsprojekt. Produkte, Preise, Beschreibungen und Dienste sind fiktiv.",
      info_terms_s2_h: "2. Kauf und Bestellung",
      info_terms_s2_l1: "Eine echte Bestellung kommt nicht zustande, da diese Seite nur Demozwecken dient.",
      info_terms_s2_l2: "Die Warenkorbfunktion ist rein visuell und für Lernzwecke gedacht.",
      info_terms_s2_l3: "Es gibt keinen realen Versand- oder Kurierdienst.",
      info_terms_s3_h: "3. Datenverarbeitung",
      info_terms_s3_p: "Das System erfasst keine echten personenbezogenen Daten; eingegebene Infos haben Democharakter.",
      info_terms_s4_h: "4. Garantie und Haftung",
      info_terms_s4_p: "Das Projekt übernimmt keine Haftung für reale Schäden; Inhalte dienen Bildungszwecken.",
      info_terms_s5_h: "5. Nutzerrechte",
      info_terms_s5_l1: "Du kannst die Seite frei durchsuchen und testen.",
      info_terms_s5_l2: "Die Inhalte dürfen zu Bildungszwecken genutzt werden.",
      info_terms_s5_l3: "Dies ist keine kommerzielle Website.",
      info_shipping_intro: "Übersicht zu Versandarten und Zahlungsoptionen.",
      info_shipping_s1_h: "Versandarten",
      info_shipping_s1_l1: "Lieferung per Kurier - 1-3 Werktage",
      info_shipping_s1_l2: "Foxpost-Automat - 2-4 Werktage",
      info_shipping_s1_l3: "Persönliche Abholung - kostenlos",
      info_shipping_s2_h: "Instrumentenspezifische Verpackung",
      info_shipping_s2_l1: "Gitarre - gepolsterter Karton",
      info_shipping_s2_l2: "Tasteninstrument - dicker Schaumstoff",
      info_shipping_s2_l3: "Lautsprecher - Palettenversand",
      info_shipping_s3_h: "Zahlungsmöglichkeiten",
      info_shipping_s3_l1: "Bankkarte",
      info_shipping_s3_l2: "Nachnahme",
      info_shipping_s3_l3: "Überweisung",
      info_shipping_s4_h: "Lieferzeit",
      info_shipping_s4_p1: "Lagerware: 1-3 Tage",
      info_shipping_s4_p2: "Bestellware: 5-14 Tage",
      info_warranty_intro: "Diese Seite dient Demozwecken; Garantieinformationen sind nicht real.",
      info_warranty_s1_h: "Garantiehinweis",
      info_warranty_s1_p: "Die aktuelle KEB-Instrumentenladen-Website ist ein Demonstrationsprojekt; Inhalte stellen keine echte Garantie dar.",
      info_warranty_s2_h: "Was bedeutet das?",
      info_warranty_s2_l1: "Produkte, Preise und Dienstleistungen sind fiktiv.",
      info_warranty_s2_l2: "Es findet keine reale Service- oder Garantieabwicklung statt.",
      info_warranty_s2_l3: "Die Oberfläche dient ausschließlich Bildungszwecken.",
      info_warranty_s3_h: "Gute Nachricht",
      info_warranty_s3_p: "Da es ein Übungsprojekt ist, kannst du die Funktionen ohne Folgen testen.",
      info_privacy_intro: "Demo-Projekt: Inhalte sind für Lernzwecke, keine reale Datenverarbeitung.",
      info_privacy_s1_h: "1. Welche Daten verarbeiten wir?",
      info_privacy_s1_p: "Eingegebene Daten landen nicht in einer echten Datenbank, sondern dienen nur zur Demonstration.",
      info_privacy_s2_h: "2. Wo werden Daten gespeichert?",
      info_privacy_s2_p: "Testdaten können lokal im Browser gespeichert werden (z. B. localStorage).",
      info_privacy_s3_h: "3. Wofür nutzen wir Daten?",
      info_privacy_s3_p: "Nur zur Simulation der Oberfläche; es gibt keine reale geschäftliche Verarbeitung.",
      info_privacy_s4_h: "4. Welche Rechte hast du?",
      info_privacy_s4_p: "Du kannst im Browser gespeicherte Daten jederzeit löschen oder ändern.",
      info_privacy_s5_h: "5. Kontakt",
      info_privacy_s5_p: "Bei Fragen schreibe an: kamu@kamuoldal.hu",
      info_contacts_intro: "Kontaktdaten - Demo-Projekt, kein realer Kundendienst.",
      info_contacts_s1_h: "Kundendienst",
      info_contacts_s1_p1: "Telefon: +36 30 000 0000",
      info_contacts_s1_p2: "E-Mail: demo@keb-hangszerbolt.hu",
      info_contacts_s2_h: "Öffnungszeiten",
      info_contacts_s2_l1: "Montag-Freitag: 9:00-18:00",
      info_contacts_s2_l2: "Samstag: 10:00-14:00",
      info_contacts_s2_l3: "Sonntag: geschlossen",
      info_contacts_s3_h: "Showroom",
      info_contacts_s3_p1: "Pecs, Fo utca 12.",
      info_contacts_s3_p2: "Kostenloses Parken vor dem Geschäft.",
      search: "Suche...",
      promo_title: "Aktionen",
      promo_sub: "Wöchentliche Rabatte",
      jump: "Springen",
      rec_title: "Empfohlen",
      rec_sub: "Beliebte Instrumente",
      promo_tag: "Jetzt kaufen!",
      view: "Ansehen",
      promo_title_long: "Aktionen",
      promo_desc: "Aktuelle Wochenrabatte. Klicke für Details.",
      promo_cart: "Aktions-Warenkorb",
      rec_title_long: "Empfohlene Instrumente",
      rec_desc: "Auswahl der beliebtesten Produkte.",
      view_all: "Gesamtes Sortiment",
      why_desc: "Schnelle Bestellung, sichere Verpackung, musikerfreundlicher Support.",
      feature_safe_title: "Sichere Verpackung",
      feature_safe_desc: "Doppelter Schutz, unterwegs sicher.",
      feature_fast_title: "Schnelle Lieferung",
      feature_fast_desc: "Lagerware in 24-48 Stunden.",
      feature_real_title: "Echte Musiker",
      feature_real_desc: "Empfehlungen von aktiven Musikern.",
      reviews_desc: "Ein paar Worte von Musikern.",
      quote_1_text: "Freundliche Seite, ich habe schnell gefunden, was ich brauchte.",
      quote_2_text: "Tolle Instrumente, faire Preise. Sehr zu empfehlen!",
      quote_3_text: "Schnelle Bestellung und professionelle Verpackung.",
      quote_4_text: "Endlich ein musikerfreundlicher Shop.",
      quote_title: "Bewertung schreiben",
      name: "Name",
      tag_site: "Die Seite",
      tag_gitar: "Gitarre",
      tag_bass: "Bassgitarre",
      tag_drum: "Schlagzeug",
      tag_keys: "Tasten",
      tag_mic: "Mikrofon",
      tag_speakers: "Lautsprecher",
      tag_accessories: "Zubehör",
      tab_products: "Produkte",
      tab_about: "Über uns",
      tab_other: "Sonstiges",
      wishlist_page_title: "Wunschliste",
      wishlist_page_desc: "Hier siehst du die mit Herz gespeicherten Produkte.",
      wishlist_clear: "Liste leeren",
      wishlist_empty: "Noch keine gespeicherten Produkte.",
      wishlist_open: "Öffnen",
      wishlist_remove: "Löschen",
      tab_services: "Dienstleistungen",
      wishlist_title: "Wunschliste",
      chat_title: "Chat",
      chat_intro: "Hier kannst du anderen Nutzern zu Anzeigen oder anderen Themen schreiben.",
      chat_threads: "Unterhaltungen",
      chat_empty: "Du hast noch keine Nachrichten.",
      chat_user: "Benutzer",
      chat_write: "Nachricht schreiben...",
      chat_badge_one: "1 Nachricht",
      chat_badge_many: "Neue Nachrichten",
      wishlist_added: "Zur Wunschliste hinzugefügt!",
      wishlist_view: "Wunschliste anzeigen",
      chat_item: "Anzeige",
      chat_login_required: "Für den Chat ist eine Anmeldung erforderlich.",
      video_caption: "Aktuelles Community-Video. Oben wechseln Schnelllinks zwischen Gebrauchtmarkt und Bandfinder.",
      video_link_used: "Gebrauchtmarkt",
      video_link_band: "Bandfinder-Seite",
      video_muted: "Stumm",
      video_unmuted: "Mit Ton",
      side_panel: "Menü",
      privacy: "Datenschutz",
      shipping: "Versand",
      terms: "AGB",
      warranty: "Garantie",
      contacts: "Kontakt",
      footer_pay_title: "Sicheres Einkaufen und Bezahlen",
      footer_pay_desc: "Sicher bezahlen über eine verschlüsselte Verbindung. (Testseite, nicht real)",
      footer_bank_transfer: "Banküberweisung",
      footer_benefits: "Vorteile",
      benefit_warranty: "3 Jahre Garantie",
      benefit_refund: "30 Tage Geld-zurück",
      benefit_service: "Service und Reparatur",
      benefit_support: "Experten-Support",
      benefit_test: "Testseite",
      footer_services: "Dienstleistungen",
      shipping_pay: "Versand und Zahlung",
      footer_copyright: "© 2025 KEB Instrumentenladen - Alle Rechte vorbehalten. Prüfungsseite.",
      no_results: "Keine Ergebnisse.",
      cat_gitar: "Gitarre",
      cat_bass: "Bassgitarre",
      cat_drum: "Schlagzeug",
      cat_keys: "Tasteninstrument",
      cat_mic: "Mikrofon",
      cat_speakers: "Lautsprecher",
      cat_accessories: "Zubehör",
      cat_accessories_desc: "Zubehör, Kabel, Ständer und alles Kleine an einem Ort.",
      cat_bass_desc: "Tiefer Bereich, straffer Groove, moderne und Vintage-Sounds.",
      cat_drum_desc: "Akustische und elektronische Drums für Einsteiger und Profis.",
      cat_keys_desc: "Synths, Stage-Pianos und Instrumente fürs Üben zu Hause.",
      cat_mic_desc: "Ausgewählte Modelle für Bühne, Studio und Streaming.",
      cat_speakers_desc: "Studiomonitore, Party-Lautsprecher und tragbare Favoriten.",
      title_cat_gitar: "KEB Gitarren",
      title_cat_bass: "KEB Bassgitarren",
      title_cat_drum: "KEB Schlagzeuge",
      title_cat_keys: "KEB Tasteninstrumente",
      title_cat_mic: "KEB Mikrofone",
      title_cat_speakers: "KEB Lautsprecher",
      title_cat_accessories: "KEB Zubehör",
      min_label: "Min",
      max_label: "Max",
      huf_label: "HUF",
      why_title: "Warum wir empfehlen",
      shipping_title: "Versand",
      shipping_desc1: "Auf Lager: 1–3 Tage · Bestellung: 5–14 Tage",
      shipping_desc2: "Sichere Verpackung und musikerfreundlicher Service.",
      reviews_title: "Bewertungen",
      prev: "Zurück",
      next: "Weiter",
      details: "Details",
      add_to_cart: "In den Warenkorb",
      added_to_cart_btn: "Hinzugefügt!",
      sample: "Klangprobe:",
      sample_title: "Klangprobe",
      reviews: "Bewertungen:",
      loading: "Lädt...",
      product_desc: "{name} aus der Kategorie {category}. Premium-Qualität, zuverlässiger Klang.",
      spec_category: "Kategorie",
      spec_shipping: "Versand: 24-48 Std. auf Lager",
      spec_warranty: "Garantie: 3 Jahre",
      spec_setup: "Setup: erste Stimmung inklusive",
      why_text: "Warum dieses {category}-Instrument? Stabiler Klang und robuste Verarbeitung.",
      write_review: "Bewertung schreiben...",
      send: "Senden",
      added_to_cart: "In den Warenkorb gelegt!",
      must_login_review: "Bitte anmelden, um zu bewerten!",
      delete: "Löschen",
      review_already: "Du hast bereits bewertet.",
      review_need_text: "Schreibe etwas und wähle Sterne!",
      review_exists_alert: "Du hast bereits bewertet!",
      confirm_delete: "Sicher löschen?",
      no_reviews: "Noch keine Bewertungen.",
      network_error: "Netzwerkfehler",
      bad_json: "Ungültige JSON-Antwort",

      email_label: "E-Mail",
      register_title: "Registrierung",
      register_success: "Registrierung erfolgreich!",
      register_error: "Fehler:",

      account_title: "Konto",
      account_back: "← Zurück zur Startseite",
      account_login_tab: "Login",
      account_register_tab: "Registrierung",
      account_admin_tab: "Admin",
      account_login_title: "Login",
      account_register_title: "Registrierung",
      account_admin_title: "Admin-Login",
      account_username_or_email: "Benutzername oder E-Mail",
      account_password: "Passwort",
      account_username: "Benutzername",
      account_admin_name: "Admin-Name",
      account_username_hint: "3-32 Zeichen, mit Buchstaben starten, nur Buchstaben/Zahlen/._-",
      account_login_btn: "Login",
      account_register_btn: "Registrierung",
      account_admin_btn: "Einloggen",
      account_welcome: "Willkommen {name}!",
      account_profile_upload: "Profilbild hochladen",
      account_delete: "Konto löschen",
      account_logout: "Logout",
      account_required_fields: "✖ Alle Felder sind Pflicht!",
      account_fix_fields: "✖ Bitte korrigiere die ungültigen Felder.",
      account_username_len: "✖ Benutzername muss 3-32 Zeichen lang sein.",
      account_username_format: "✖ Benutzername muss mit einem Buchstaben beginnen und darf nur Buchstaben/Zahlen/._- enthalten.",
      account_username_separators: "✖ Zwei Sonderzeichen hintereinander sind nicht erlaubt.",
      account_username_letters: "✖ Benutzername muss mindestens 3 Buchstaben enthalten.",
      account_username_repeat: "✖ Zu viele wiederholte Zeichen.",
      account_invalid_email: "✖ Ungültiges E-Mail-Format.",
      account_password_min: "✖ Passwort muss mindestens 6 Zeichen haben.",
      account_login_success: "✔ Login erfolgreich!",
      account_register_success: "✔ Registrierung erfolgreich! Bitte einloggen.",
      account_invalid_login: "✖ Falsche Daten!",
      account_not_admin: "✖ Kein Admin-Konto!",
      account_token_expired: "✖ Token abgelaufen. Bitte neu einloggen.",
      account_no_file: "Keine Datei ausgewählt!",

      profile_title: "Profil",
      profile_email_label: "E-Mail:",
      profile_back: "⬅ Zurück",
      profile_logout_btn: "Logout",
      profile_upload_btn: "Profilbild hochladen",
      profile_file_missing: "Keine Datei ausgewählt!",
      profile_updated: "Profil aktualisiert!",
      profile_loading: "Lädt...",
      theme_toggle: "Thema wechseln",

      used_title: "Gebrauchtmarkt",
      used_short_desc: "Gebrauchte Sachen.",
      used_subtitle: "Stelle dein Gear ein oder verhandle faire Angebote.",
      used_desc: "Nutzer können Angebote machen, der Verkäufer kann annehmen oder ablehnen.",
      used_add_title: "Artikel hochladen",
      used_login_hint: "Bitte einloggen, um einen Artikel hochzuladen.",
      used_title_label: "Titel",
      used_price_label: "Preis (HUF)",
      used_category_label: "Kategorie",
      used_condition_label: "Zustand",
      used_desc_label: "Beschreibung",
      used_image_label: "Bild",
      used_submit: "Hochladen",
      used_search: "Suche...",
      used_all: "Alle",
      used_mode_all: "Alle Angebote",
      used_mode_mine: "Meine Artikel",
      used_filter_btn: "Filtern",
      used_empty: "Noch keine Artikel.",
      used_active: "Verfügbar",
      used_sold: "Verkauft",
      used_sold_hint: "Dieser Artikel wurde verkauft.",
      used_login_offer: "Bitte einloggen, um ein Angebot zu machen.",
      contact_user_btn: "Kontakt aufnehmen",
      offer_list_title: "Angebote",
      offer_price_placeholder: "Angebot (HUF)",
      offer_send: "Angebot senden",
      messages_btn: "Nachrichten",
      offer_none: "Noch keine Angebote.",
      offer_pending: "Offen",
      offer_accepted: "Angenommen",
      offer_rejected: "Abgelehnt",
      offer_accept: "Annehmen",
      offer_reject: "Ablehnen",
      used_condition_new: "Neuwertig",
      used_condition_good: "Gut",
      used_condition_used: "Gebraucht",
      used_condition_fix: "Reparatur nötig",
      filter: "Filter",
      manufacturer: "Hersteller",
      price_category: "Preiskategorie",
      order_state: "Verfügbarkeit",
      instant_shipping: "Sofort lieferbar",
      rating: "Bewertung",
      vibe_guitar_offers: "Gitarrenangebote",
      vibe_bass_news: "Bass-Neuheiten",
      vibe_used_market: "Gebrauchtmarkt",
      vibe_band_search: "Bandsuche",
      cat_gitar_desc: "Elektrische, akustische und klassische Modelle an einem Ort.",
      page_label: "Seite",

      band_title: "Bandfinder",
      band_short_desc: "Finde eine Band.",
      band_subtitle: "Finde Musiker und Bands nach Stil, Stadt und Instrument.",
      band_desc: "Erstelle ein Bandprofil, gib an, wen ihr sucht, und nimm Kontakt auf.",
      band_add_title: "Neue Band",
      band_login_hint: "Bitte einloggen, um eine Band zu erstellen.",
      band_name_label: "Bandname",
      band_genre_label: "Stil",
      band_city_label: "Stadt",
      band_looking_label: "Gesucht",
      band_desc_label: "Beschreibung",
      band_contact_label: "Kontakt",
      band_contact_placeholder: "E-Mail / Insta",
      band_image_label: "Bandbild",
      band_submit: "Band speichern",
      band_update: "Band aktualisieren",
      band_edit_mode: "Bearbeitungsmodus aktiv.",
      band_edit_cancel: "Bearbeitung abbrechen",
      band_search: "Suche...",
      band_genre_filter: "Stil",
      band_city_filter: "Stadt",
      band_looking_filter: "Instrument",
      band_filter_btn: "Filtern",
      band_empty: "Noch keine Bands.",
      band_searching_for: "Gesucht",
      band_chat_prefill: "Hallo! Ich interessiere mich für eure Band",
      posted_by: "Erstellt von",
      edit: "Bearbeiten",

      profile_used_title: "Meine Verkäufe",
      profile_used_empty: "Keine Artikel hochgeladen.",
      profile_bands_title: "Meine Bands",
      profile_bands_empty: "Noch kein Bandprofil.",
      profile_rating_title: "Profilbewertung",
      profile_rating_empty: "Noch keine Bewertungen.",
      profile_rating_placeholder: "Schreibe eine kurze Bewertung...",
      profile_rating_send: "Bewertung senden",
      profile_rating_login: "Bitte einloggen, um zu bewerten.",

      verify_email_sent: "Bestätigungs‑E-Mail gesendet. Bitte Posteingang prüfen.",
      verify_pending: "Überprüfung läuft...",
      verify_success: "Bestätigung erfolgreich",
      verify_resend_sent: "Bestätigungs‑E-Mail erneut gesendet.",
      verify_resend_error: "Fehler: ",
      verify_resend_btn: "Bestätigungs‑E-Mail erneut senden"
    }
  };

  function normalizeLang(lang) {
    const raw = String(lang || "").trim().toLowerCase();
    return DICT[raw] ? raw : "hu";
  }

  function getLang() {
    return normalizeLang(localStorage.getItem(LANG_KEY) || "hu");
  }

  function tr(lang, key) {
    return (DICT[lang] && DICT[lang][key]) || (DICT.hu && DICT.hu[key]) || "";
  }

  function applySingleElementTranslations(el, lang) {
    if (!el || !el.getAttribute) return;

    const keyText = el.getAttribute("data-i18n");
    if (keyText) {
      const val = tr(lang, keyText);
      if (val) el.textContent = val;
    }

    const keyPh = el.getAttribute("data-i18n-placeholder");
    if (keyPh) {
      const val = tr(lang, keyPh);
      if (val) el.placeholder = val;
    }

    const keyPhLegacy = el.getAttribute("data-i18n-ph");
    if (keyPhLegacy) {
      const val = tr(lang, keyPhLegacy);
      if (val) el.placeholder = val;
    }

    const keyHtml = el.getAttribute("data-i18n-html");
    if (keyHtml) {
      const val = tr(lang, keyHtml);
      if (val) el.innerHTML = val;
    }

    const keyTitle = el.getAttribute("data-i18n-title");
    if (keyTitle) {
      const val = tr(lang, keyTitle);
      if (val) el.title = val;
    }

    const keyValue = el.getAttribute("data-i18n-value");
    if (keyValue) {
      const val = tr(lang, keyValue);
      if (val) el.value = val;
    }

    const keyAria = el.getAttribute("data-i18n-aria-label");
    if (keyAria) {
      const val = tr(lang, keyAria);
      if (val) el.setAttribute("aria-label", val);
    }
  }

  function applyNodeTranslations(root, lang) {
    if (!root || !root.querySelectorAll) return;
    if (root.nodeType === 1) applySingleElementTranslations(root, lang);

    root.querySelectorAll("[data-i18n]").forEach((el) => {
      applySingleElementTranslations(el, lang);
    });

    root.querySelectorAll("[data-i18n-placeholder]").forEach((el) => {
      applySingleElementTranslations(el, lang);
    });

    root.querySelectorAll("[data-i18n-ph]").forEach((el) => {
      applySingleElementTranslations(el, lang);
    });

    root.querySelectorAll("[data-i18n-html]").forEach((el) => {
      applySingleElementTranslations(el, lang);
    });

    root.querySelectorAll("[data-i18n-title]").forEach((el) => {
      applySingleElementTranslations(el, lang);
    });

    root.querySelectorAll("[data-i18n-value]").forEach((el) => {
      applySingleElementTranslations(el, lang);
    });

    root.querySelectorAll("[data-i18n-aria-label]").forEach((el) => {
      applySingleElementTranslations(el, lang);
    });
  }

  function applyLang(lang) {
    const normalized = normalizeLang(lang);
    document.documentElement.lang = normalized;
    document.querySelectorAll(".lang-pill").forEach((btn) => {
      btn.classList.toggle("active", btn.dataset.lang === normalized);
    });

    applyNodeTranslations(document, normalized);

    if (typeof window.onLangChange === "function") {
      window.onLangChange(normalized);
    }
    window.dispatchEvent(new CustomEvent("lang:changed", { detail: { lang: normalized } }));
  }

  function setLang(lang) {
    const normalized = normalizeLang(lang);
    localStorage.setItem(LANG_KEY, normalized);
    applyLang(normalized);
  }

  document.addEventListener("click", (e) => {
    const btn = e.target.closest(".lang-pill");
    if (!btn) return;
    setLang(btn.dataset.lang);
  });

  const initial = getLang();
  applyLang(initial);

  const mo = new MutationObserver((mutations) => {
    const activeLang = getLang();
    mutations.forEach((m) => {
      m.addedNodes.forEach((node) => {
        if (!node || node.nodeType !== 1) return;
        applyNodeTranslations(node, activeLang);
      });
    });
  });
  mo.observe(document.documentElement || document.body, { childList: true, subtree: true });

  window.addEventListener("storage", (e) => {
    if (e.key !== LANG_KEY) return;
    applyLang(getLang());
  });

  window.SH_LANG = {
    setLang,
    getLang,
    refresh: () => applyLang(getLang()),
    t: (key) => {
      const lang = getLang();
      return (DICT[lang] && DICT[lang][key]) || (DICT.hu && DICT.hu[key]) || key;
    }
  };
})();

